### ISSUE TITLE
Question requirement indications aren't showing up

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1129]
There has been code in the templates for a long time to show which certificate level each question is required for.

But the way it was being determined wasn't working

**Comment by pkqk** [comment]
Fixed by #1126 

This will also speed up the questionnaire as it should reduce the number of queries on the database by quite a bit.

**Comment by shevski** [comment]
Still not fixed - e.g. 'Is there a link to your data from your main website?' is 'standard' level,
 however:
1. This is not displayed in questionnaire (see screenshot)
2. Follow up question for which URL erroniously says this is required for raw level

![screen shot 2015-06-22 at 16 53 24](https://cloud.githubusercontent.com/assets/1260289/8286048/3e123a6c-18ff-11e5-88f5-170d0341068d.png)

**Comment by shevski** [comment]
P.S. This is on the live site! e.g. https://certificates.theodi.org/surveys/gb/BlUsP9fs2Q/take
